### ISSUE TITLE
请教一下，您是如何进行debug的？

### ISSUE THREAD

**Issue by ycdm** [bin456789/NoWechatRevoke#1]
对于xposed的插件，是如何debug的？

**Comment by bin456789** [comment]
我也不太懂，我都是用log.d打印变量什么的，没有试过单步调试。
有时调试要得到调用堆栈，可以hook住函数以后抛出异常并打印调用堆栈。
还有就是hook不住某个函数的话，控制台会显示异常。
就这点经验了，希望帮到你。。

**Comment by ycdm** [comment]
@bin456789 
能交流一下你当时是怎么知道，该方法可以影响到微信撤回的呢？
思路是怎么样的？

**Comment by bin456789** [comment]
@ycdm 我想撤回的消息在数据库中里一定有什么标记，于是网上找到方法读取微信的数据库，然后发现撤回的消息的某个字段会标记为10000，于是源码中搜索10000，找到方法后hook住然后打印调用堆栈，就找到大概的位置了，所以也就有上面那点经验。
