### ISSUE TITLE
建议QQ标出撤回消息！

### ISSUE THREAD

**Issue by kuilei0926** [bin456789/NoWechatRevoke#10]
1.4.1对QQ和微信已经失效！1.4之前对QQ的还能用！QQ没有撤回标记用起来真。。。。

**Comment by kuilei0926** [comment]
@bin456789

**Comment by bin456789** [comment]
这个已经弃坑了。
请转战 https://github.com/fkzhang/WechatUnrecalled 和 https://github.com/fkzhang/QQUnrecalled
