### ISSUE TITLE
今天更新了6.3.13

### ISSUE THREAD

**Issue by niray** [bin456789/NoWechatRevoke#9]
更新后,功能失效..

' setArgs(new String[]{"q", "J"}, new String[]{"ah", "tD", "rs", "bCw"}, new String[]{"aXP"});'

这里的q J ah Td  等混淆名是如何发现的..这样我们也能帮忙更新一下

**Comment by bin456789** [comment]
以6.3.13为例，打开com.tencent.mm.model.bd，搜索revokemsg然后看看周围的代码，就能找到这些东西了。
另外这个项目已经弃坑了，因为已经有功能更强大的 https://github.com/fkzhang/WechatUnrecalled

**Comment by mengyyy** [comment]
留个纪念
